# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Document/'
            - '../src/Kernel.php'

    App\Repository\EntityRepository\CandidateRepository:
        arguments:
            $registry: '@doctrine'

    App\Controller\CandidateCrudController:
        arguments:
            - $resumeUploadService : '@App\Services\Impl\ResumeUploadService'
    App\Services\Impl\ResumeUploadService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $uploadDir: '%env(UPLOAD_DIR)%'

################################################################
    #configuring the service locator (:
    App\Transformation\Strategy\CandidateTransformationStrategy:
        tags:
            - { name: 'app.transform_to_document_strategy', type: 'candidate' }
            - { name: 'app.transform_to_entity_strategy', type: 'candidate' }
    App\Transformation\Strategy\EvaluatorTransformationStrategy:
        tags:
            - { name: 'app.transform_to_document_strategy', type: 'evaluator' }
            - { name: 'app.transform_to_entity_strategy', type: 'evaluator' }

    app.transform_to_document_strategy_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                candidate: '@App\Transformation\Strategy\CandidateTransformationStrategy'
                evaluator: '@App\Transformation\Strategy\EvaluatorTransformationStrategy'

    app.transform_to_entity_strategy_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        arguments:
            -
                candidate: '@App\Transformation\Strategy\CandidateTransformationStrategy'
                evaluator: '@App\Transformation\Strategy\EvaluatorTransformationStrategy'


    App\Transformation\Factory\TransformationStrategyFactory:
        arguments:
            $documentStrategies: '@app.transform_to_document_strategy_locator'
            $entityStrategies: '@app.transform_to_entity_strategy_locator'

    App\Adapter\DataTransformationAdapter:
        arguments:
            $transformationStrategyFactory: '@App\Transformation\Factory\TransformationStrategyFactory'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
