# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'
        routing:
            'App\Message\Candidate\CandidateCreatedMessage': async
            'App\Message\Candidate\CandidateUpdatedMessage': async
            'App\Message\Candidate\CandidateDeletedMessage': async

            'App\Message\User\UserCreatedMessage': async
            'App\Message\User\UserUpdatedMessage': async
            'App\Message\User\UserDeletedMessage': async

            'App\Message\Interview\InterviewCreatedMessage': async


